version: "2.1"
services:

  glo-services:
    container_name: glo-services
    hostname: glo-services
    build: .
    image: glo-services
    volumes:
      - .:/glo-services

    ports:
      - 8080:8080

